# Generated by Django 3.2.13 on 2022-06-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipManagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('submitted', models.BooleanField(default='False')),
                ('doc_name', models.CharField(max_length=200)),
                ('client_url', models.CharField(max_length=200, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.clientmodel')),
                ('relationship_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.relationshipmanagermodel')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='console.requestmodel')),
                ('file', models.FileField(upload_to='documents/')),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
